### ISSUE TITLE
JSON export incomplete

### ISSUE THREAD

**Issue by IntranetFactory** [grommet/grommet-designer#92] opened 2021-06-02 17:50 UTC
I opened https://designer.grommet.io/undefined?id=Card-eric-soderberg-hpe-com&mode=edit, select share, Download - the resulting file is just 413 bytes and seems to be truncated:

```json
{"name":"Card","screens":{"1":{"id":1,"root":25,"name":"Card"}},"screenOrder":[1],"components":{"3":{"id":3,"type":"Box","props":{"align":"center","pad":"small","background":{"0":"b","1":"r","2":"a","3":"n","4":"d","color":"white","image":"url('data:image/svg+xml;utf8,<svgxmlns=\"http://www.w3.org/2000/svg\"width=\"130\"height=\"192\"viewBox=\"240140192\">\n<gfill=\"none\"fill-rule=\"evenodd\">\n<pathstroke=\"
```

**Comment by ericsoderberghp** [comment] 2021-06-02 20:22
It seems to be working for me. If I export from one browser and then import in a different browser, it works. The JSON format is a compact description of the design. What were you expecting to see?

**Comment by IntranetFactory** [comment] 2021-06-02 20:54
The above code is the code from the downloaded file. It seems to end early with `<pathstroke=\"`   I've renamed the whole file and attached it: [Card.json.txt](https://github.com/grommet/grommet-designer/files/6587381/Card.json.txt)

Uploading fails with `Unexpected end of JSON input`.  I'm using Chrome 90 on Windows.

**Comment by ericsoderberghp** [comment] 2021-06-02 21:02
Interesting. I see the truncation you have sent. It looks like it can be reproduced on Chrome and Firefox but not on Safari. I will look into it ...

**Comment by ericsoderberghp** [comment] 2021-06-03 01:04
Thanks for reporting the issue. It should be fixed now.

**Closed as completed by ericsoderberghp** 2021-06-03 01:04 UTC
